### ISSUE TITLE
Adding the FC Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [KeithSloan/GDML#1]
@KeithSloan Can we clean up the README.md before we add this to the Addon Manager?
Specifically, the large warning at the top ?

**Comment by KeithSloan** [comment]
Have made some changes. I realise that it gets view in a subwindow in the AddonManager, but don't know how I would check what it looks like given it does not come up as an installable option yet.
Let me know if more is required

**Comment by luzpaz** [comment]
:+1:  
Added in https://github.com/FreeCAD/FreeCAD-addons/commit/13a663df0deb54bea100d492f71e551b82635276
