### ISSUE TITLE
Solids to initially concentrate on

### ISSUE THREAD

**Issue by KeithSloan** [KeithSloan/GDML#10]
Parsing : ../SampleFiles/CERN/lhcbvelo.gdml

List of Solids in : ../SampleFiles/CERN/lhcbvelo.gdml
=====================================================
box
tube
union
trap
subtraction
cone
trd
polycone

Parsing : ../SampleFiles/CERN/Alice/alice.gdml

List of Solids in : ../SampleFiles/CERN/Alice/alice.gdml
========================================================
polyhedra
xtru
polycone
cone
tube
subtraction
box
union
trap
intersection
trd
para
arb8
torus
eltube
cutTube

**Comment by lambdam94** [comment]
oneBox.gdml
-> ok under Freecad 0.18 and Freecad 0.19.AppImage
![oneBox](https://user-images.githubusercontent.com/62946076/80372377-be26b800-8893-11ea-9cf5-0c3a72ba2351.png)

**Comment by lambdam94** [comment]
oneTube.gdml
-> ok under Freecad 0.18 and Freecad 0.19.AppImage
![oneTube](https://user-images.githubusercontent.com/62946076/80372715-3db48700-8894-11ea-9f9c-6e509c919429.png)
