### ISSUE TITLE
Can not create torus.

### ISSUE THREAD

**Issue by roiiiu** [KeithSloan/GDML#101]
![image](https://user-images.githubusercontent.com/11494827/196168094-4e5009dc-b724-493c-b339-b454129b77ce.png)
I get this problem when creating torus

` FreeCad :0.20.1`

**Comment by roiiiu** [comment]
It worked fine when i comment the problem code and change the 'myTorus' to 'obj' in the next line.
![image](https://user-images.githubusercontent.com/11494827/196170424-75291f6d-8f1d-4a99-bd21-3dce91568370.png)

**Comment by KeithSloan** [comment]
Thanks - Code should have been

```
       if FreeCAD.GuiUp:
            obj.ViewObject.Visibility = True
            ViewProvider(obj.ViewObject)
```
Should be fixed in latest version.
