### ISSUE TITLE
Failed to create face from wire

### ISSUE THREAD

**Issue by ParticleTruthSeeker** [KeithSloan/GDML#157]
Hi,

Is there a common solution to this error message?

Cheers

**Comment by mhindi2** [comment]
Could you please email me the FreeCAD file that produces the message? Thanks.

**Comment by ParticleTruthSeeker** [comment]
Sent

**Comment by ParticleTruthSeeker** [comment]
Hello everyone,

This turned out to be a trivial sketching error unrelated to the gdml workbench. 

It seems the sketch line end points aren't quite snapping on to each other resulting in some unclosed wires and the aforementioned error.

Many thanks to @mhindi2 for the time and kind help he offered to help resolve this issue and for to the gdml workbench developers.

Cheers!
