### ISSUE TITLE
ElTube placement

### ISSUE THREAD

**Issue by lambdam94** [KeithSloan/GDML#17]
Hello Keith,

ElTube have a shift placement.
That could be fix (line 654 GDMLObject) by adding a "-" 
       base = FreeCAD.Vector(0,0,(fp.dz*mul)/2)
->
       base = FreeCAD.Vector(0,0,-(fp.dz*mul)/2)

Thanks,
Regards
Dam

**Comment by KeithSloan** [comment]
Hopefully, now fixed.

**Comment by lambdam94** [comment]
Thanks!
Regards
Dam
