### ISSUE TITLE
improvement: expand volume without lxml

### ISSUE THREAD

**Issue by lambdam94** [KeithSloan/GDML#18]
Hello Keith,

normaly, we cannot expand volume without lxml.
But I tried, to replace line 542 in GDMLcommand.py by the following lines and it seems working well

Regards
Dam

               #import lxml.etree  as ET 
               try :
                     from lxml.etree as ET
               except ImportError:
                     try:
                         import xml.etree.ElementTree as ET
                     except ImportError:
                         print('pb xml lib not found')
                         sys.exit()

**Comment by lambdam94** [comment]
Thanks Keith!
Regards
Dam

**Comment by lambdam94** [comment]
Hello again Keith,

I give you a bad advice,
could you please replace 
# line 544
                 from lxml.etree as ET
by
# line 544
                 from lxml.etree import ET

Sorry and thanks!
Regards
Dam

**Comment by KeithSloan** [comment]
Funny I nearly questioned that when I saw it

**Comment by lambdam94** [comment]
Thanks!
Regards
Dam
