### ISSUE TITLE
Exporting GDML with tessellated volumes hangs FreeCAD

### ISSUE THREAD

**Issue by alowell-ssl** [KeithSloan/GDML#55]
Hi,

I followed your instructions to open a new GDML project.  I then create a part with a body that I form from extruding a sketch (using Part Design WB).  I am able to tessellate the body, and then drag the part into the World Volume part.  When I try to export to GDML, FreeCAD hangs.

I tried creating a geometry with the simple GDML volume tools and I was able to successfully export a GDML in that case.  So, it seems that the problem is when I try to include tessellated bodies.

I'm using:
FreeCAD-asm3-Daily-Conda-Py3-Qt5-20211015-glibc2.12-x86_64.AppImage

**Comment by KeithSloan** [comment]
Thanks for reporting.

Please could you supply a problem file - see email address at bottom README.md, replacing [dot] with a dot and [at] with an @.

**Comment by alowell-ssl** [comment]
Fixed, thanks very much :)
