### ISSUE TITLE
getMult improvement

### ISSUE THREAD

**Issue by lambdam94** [KeithSloan/GDML#6]
Hello Keith

could you please add a little more length param (dm, umn nm, etc.) in getMult?
Thanks!

Exemple:
def getMult(lunit) :
    if lunit == 'mm' or lunit == None :        return(1)
    elif lunit == 'cm' :        return(10)
    elif lunit == 'm' :        return(1000)
    elif lunit == 'dm' :        return(100)
    elif lunit == 'km' :        return(1000000)
    elif lunit == 'um' :        return(0.001)
    elif lunit == 'nm' :        return(0.000001)
    print('unit not handled : '+lunit)
   
   
Regards,
Dam

**Comment by KeithSloan** [comment]
Thanks - Actioned
