### ISSUE TITLE
AddonManager should display more info about 3rd-Party dependency `gmsh-dev`

### ISSUE THREAD

**Issue by luzpaz** [KeithSloan/GDML#92]
![Screenshot_20220407_112443](https://user-images.githubusercontent.com/4140247/162235186-3baf6716-f156-45d7-affc-a380843e4421.png)

Maybe the dialog can display a hyperlink back to the GDML README that discusses where and how to install `gmsh-dev` to make it more convenient for the user to orient to this requirement?

**Comment by KeithSloan** [comment]
Maybe but why can it not install it? For non FreeCAD you can install with python3 pip -m install gmsh-dev.
