### ISSUE TITLE
Something wrong with update

### ISSUE THREAD

**Issue by porosev** [KeithSloan/GDML#99]
Dear Keith,

Today, when I run FreeCAD and try to update workbench it reports errors...

![Git_1](https://user-images.githubusercontent.com/5234963/183963463-1f739138-561c-47e5-97ce-d896a8bf7731.jpg)

**Comment by KeithSloan** [comment]
Looks like something might have got screwed with the Submodule Utils.

Try unstall and reinstalling the workbench rather than just update.

**Comment by KeithSloan** [comment]
Have removed submodule Utils and restored the files that were in Utils as a submodule.
Please try your update again.

**Comment by porosev** [comment]
Dear Keith,

Anyway something wrong with mod install/update. In reality, after installation and manual FreeCAD restart I can use GDML-workbench, switch branches etc... so, it works, but during installation stage it report strange things ;((

![Update](https://user-images.githubusercontent.com/5234963/184073971-ee575d50-3ee0-477c-8292-72a9b53ee77a.jpg)

**Comment by KeithSloan** [comment]
Out of interest what version of gitPython do you have installed? pip show gitpython

**Comment by porosev** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/5234963/184272920-66aa301e-94b9-4d13-891a-7a6bd55dca5c.jpg)

**Comment by KeithSloan** [comment]
Think there is a bug in FreeCAD Addon Manager it does not handle a repro where a submodule has been removed.

Restarting FreeCAD, the workbench has been installed.

**Comment by KeithSloan** [comment]
Hopefully now FIXED.
